#!/bin/bash

source "${BASH_SOURCE%/*}/utils.sh"

if [[ $BITBUCKET_BRANCH =~ ([A-Z]+-[0-9]+) ]]; then
  trim16 $(downcase ${BASH_REMATCH[1]})
elif [[ $BITBUCKET_BRANCH =~ release/([0-9]{4}-[0-9]{2}-[0-9]{2}) ]]; then
  trim16 $(downcase ${BASH_REMATCH[1]})
else
  trim16 $(normalize $BITBUCKET_BRANCH)
fi
