---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helm-delete-ns
  namespace: "{{ .Values.envName }}"
  annotations:
    helm.sh/resource-policy: keep
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ephemeral-webhook
subjects:
- kind: ServiceAccount
  name: ephemeral-webhook
  namespace: utils

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helm-delete
  namespace: "{{ .Values.envName }}"
  annotations:
    helm.sh/resource-policy: keep
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: ephemeral-webhook
  namespace: utils
